### ISSUE TITLE
Missing enablers short names from titles

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#292]
- I just realized that there are some enabler releases that they don't have the short name or abbreviation in parenthesis at the end of the enabler title. See below
- Also, I found a link that is not pointing to the corresponding enabler:  "OMA In-Game Communications".
So, now you need to check every single link in the home page to ensure that it points to the correct enabler. Once I find something like that, makes me wonder if we have something else wrong.

![various](https://cloud.githubusercontent.com/assets/3258579/22132321/27b3d0f6-de6e-11e6-8f9e-888a1ad95313.png)

**Comment by jmudge** [comment]
Thanks for pointing out the incorrect link for "OMA In-Game Communications"; this has been fixed in https://github.com/OpenMobileAlliance/openmobilealliance.github.io/pull/296

ACS tested this page multiple times so I'm very surprised that this error has slipped through. As you say the page clearly needs to be tested again more thoroughly.

The names of the enablers including abbreviation (whether present or not) have all been inherited from the old WordPress web page. There has not been previously been a policy of including both a long name and the portal short name on the index page. There may be some ambiguities with doing so e.g. the portal short name for "Lightweight Machine to Machine" is actually "LightweightM2M", so do we change the current index page abbreviation "LWM2M" to "LightweightM2M" to make it match the portal short name, or perhaps change it to "LwM2M" instead?

For other names the release name listed is actually the abbreviation e.g. "OMA LWM2M LOCKWIPE" where adding the short name would result in "OMA LWM2M LOCKWIPE (LWM2M_LOCKWIPE)". I'm not sure this is ideal. Nevertheless we can go ahead and make these changes.

**Comment by seanmcilroy29** [comment]
I've updated all the Short titles that have small abbreviations
